export const SEARCH_ERROR = 'SEARCH_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const SERVER_ERROR = 'SERVER_ERROR';
export const GET_RANDOM_TEXT="GET_RANDOM_TEXT";
export const GET_RANDOM_TEXT_SUCCESS="GET_RANDOM_TEXT_SUCCESS";
export const UPDATE_CURSOR="UPDATE_CURSOR";

